# name: Deploy to Google Cloud Run

# on:
#   push:
#     branches:
#     - master

# # Environment variables available to all jobs and steps in this workflow
# env:
#   GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
#   GITHUB_SHA: ${{ github.sha }}
#   GKE_ZONE: us-central1
#   IMAGE: website

# jobs:
#   deploy:
#     name: Deploy
#     runs-on: ubuntu-latest
#     steps:

#     - name: Checkout
#       uses: actions/checkout@master

#     - uses: actions/setup-node@v1
#       with:
#         node-version: '10.x'
#         registry-url: 'https://registry.npmjs.org'

#     # Create production build
#     - run: yarn install
#     - run: yarn build

#     # Setup gcloud CLI
#     - name: Authenticate into Google Cloud Platform
#       uses: actions/gcloud/auth@master
#       env:
#         GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

#     - uses: actions/gcloud/cli@master
#       with:    
#         args: config set project $GKE_PROJECT
      
#     # Build and push the Docker image
#     - name: Build
#       uses: actions/gcloud/cli@master
#       with:    
#         args: builds submit --tag gcr.io/"$GKE_PROJECT"/"$IMAGE":"$GITHUB_SHA"

#     # Deploy the Docker image
#     - name: Publish
#       uses: actions/gcloud/cli@master
#       with:
#         args: beta run deploy --image gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA
